apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: 'nacos-cluster'
  name: 'nacos-cluster'
  namespace: 'default'
spec:
  serviceName: nacos-headless-service
  replicas: 2 
  selector:
    matchLabels:
      app: 'nacos-cluster'
  template:
    metadata:
      labels:
        app: 'nacos-cluster'
      namespace: 'default'
    spec:
      initContainers:
      - image: 'busybox'
        imagePullPolicy: Always
        name: 'init-nacos-cluster'
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
          - mountPath: /web/
            name: cluster-conf
        command: ["bash", "-c", "sed -i \"s/MY_POD_IP/$MY_POD_IP/g\" /web/application.properties"]
      containers:
      - image: 'alaien/nacos-cluster'
        imagePullPolicy: Always
        name: 'nacos-cluster'
        ports:
        - name: web
          containerPort: 8848
        - name: elect
          containerPort: 7848
        env:
        - name: HEAP_SIZE
          value: 512m
        resources:
          requests:
            cpu: "100m"
          limits:
            memory: "800Mi"
        volumeMounts:
        - mountPath: /web/conf/cluster.conf
          name: cluster-conf
          subPath: cluster.conf
        - mountPath: /web/conf/application.properties
          name: cluster-conf
          subPath: application.properties

      volumes:
      - name: cluster-conf
        configMap: 
          name: nacos-cluster
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: 'nacos-cluster'
  name: nacos-cluster-service
  namespace: 'default'
spec:
  ports:
  - name: web
    port: 8848
    protocol: TCP
    targetPort: 8848
    nodePort: 30001
  selector:
    app: 'nacos-cluster'
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: 'nacos-cluster'
  name: nacos-headless-service
  namespace: 'default'
spec:
  ports:
  - name: web
    port: 8848
    protocol: TCP
    targetPort: 8848
  - name: elect
    port: 7848
    protocol: TCP
    targetPort: 7848
  selector:
    app: 'nacos-cluster'
  clusterIP: None
